// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgjsnvugfxlevhydcywc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnanNudnVnZnhsZXZoeWRjeXdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwMzYxNjgsImV4cCI6MjA1NDYxMjE2OH0.tD9wc8LaE_6tH4Oppgox8gsoRR4OhZA_1PGFmysrv-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);